#! /bin/sh

sxhkd &
nitrogen --set-scaled ~/.local/share/wallpapers/bg_27.jpg
picom &
bash /home/fuuijin/.config/polybar/launch.sh --forest &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Google-chrome desktop='^2' 
bspc rule -a Slack desktop='^10' 
bspc rule -a discord desktop='^9' 
bspc rule -a Caprine desktop='^8' 
bspc rule -a obsidian desktop='^3' 
bspc rule -a Steam desktop='^7' 
bspc rule -a notion-app desktop='^4' 
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

killall google-chrome-stable
killall slack
killall discord
killall caprine
killall obsidian
killall steam
killall notion-app

google-chrome-stable &
slack &
discord &
caprine &
obsidian &
steam-native &
notion-app &

