#! /bin/sh

### BSPC ###
INTERNAL_MONITOR="eDP"
EXTERNAL_MONITOR="HDMI-A-0"
# on first load setup default workspaces
if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
  fi
fi

#bash /home/fuuijin/.config/polybar/launch.sh --forest &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# AUTOSTART
# Helper function to check for active process, if not found starts program on the background
_run() {
    if ! pgrep -x "${1}" &>/dev/null; then
        "$@" &
    fi
}

source ~/.zshrc
fc-cache -fv &

_run sxhkd -m -1 > /tmp/sxhkd.log
_run ntfd
_run pcmanfm -d
_run nm-applet

setbg.sh &

_run picom 

bspwm_setup_monitors.sh &
